export const commentaries = [
    {
        id: 1,
        matchId: 1,
        commentary: {
            innings1: [
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 14.1,
                    runs: 4,
                    event: "F",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 14.1,
                    runs: 4,
                    event: "F",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 14.1,
                    runs: 4,
                    event: "F",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.6,
                    runs: 4,
                    event: "F",
                    overSeparator: {
                        score: 54,
                        wickets: 8,
                        over_summary: "Wd 0 2 0 0 0 2",
                        runs: 5,
                        batStrikerId: 1,
                        batStrikerName: "Aayan Afzal Khan",
                        batStrikerRuns: 14,
                        batStrikerBalls: 17,
                        batNonStrikerIds: 2,
                        batNonStrikerName: "Adhitya Shetty",
                        batNonStrikerRuns: 2,
                        batNonStrikerBalls: 4,
                        bowlId: 3,
                        bowlName: "Noor Ahmad",
                        bowlOvers: 2,
                        bowlMaidens: 0,
                        bowlRuns: 8,
                        bowlWickets: 1,
                        overNum: 13.6
                    },
                    timestamp: 1640428814837
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.5,
                    runs: 4,
                    event: "F",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.4,
                    runs: 4,
                    event: "F",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.3,
                    runs: 0,
                    event: "W",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.2,
                    runs: 4,
                    event: "F",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.2,
                    runs: 0,
                    event: "WD",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.1,
                    runs: 3,
                    event: "NONE",
                    timestamp: 1640428814837,
                },
            ],
            innings2: [
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 14.1,
                    runs: 4,
                    event: "F",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 14.1,
                    runs: 4,
                    event: "F",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 14.1,
                    runs: 4,
                    event: "F",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.6,
                    runs: 4,
                    event: "F",
                    overSeparator: {
                        score: 54,
                        wickets: 8,
                        over_summary: "Wd 0 2 0 0 0 2",
                        runs: 5,
                        batStrikerId: 1,
                        batStrikerName: "Aayan Afzal Khan",
                        batStrikerRuns: 14,
                        batStrikerBalls: 17,
                        batNonStrikerIds: 2,
                        batNonStrikerName: "Adhitya Shetty",
                        batNonStrikerRuns: 2,
                        batNonStrikerBalls: 4,
                        bowlId: 3,
                        bowlName: "Noor Ahmad",
                        bowlOvers: 2,
                        bowlMaidens: 0,
                        bowlRuns: 8,
                        bowlWickets: 1,
                        overNum: 13.6
                    },
                    timestamp: 1640428814837
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.5,
                    runs: 4,
                    event: "F",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.4,
                    runs: 4,
                    event: "F",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.3,
                    runs: 0,
                    event: "W",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.2,
                    runs: 4,
                    event: "F",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.2,
                    runs: 0,
                    event: "WD",
                    timestamp: 1640428814837,
                },
                {
                    text: "Noor Ahmad to Afzal Khan, B0$",
                    overs: 13.1,
                    runs: 3,
                    event: "NONE",
                    timestamp: 1640428814837,
                },
            ],
        },
        miniScore: {
            innings: 1,
            batTeamId: 6,
            scores: 54,
            wickets: 3,
            overs: 6.2,
            target: 195,
            lastWicketText: "Sailles Jaishankar  lbw b Izharulhaq Naveed 0(1)  - 54/10 in 14.4 ov.",
            batsmanStriker: {
                id: 1,
                name: "Aayan Afzal Khan",
                nickname: "Aayan",
                balls: 17,
                runs: 14,
                dots: 10,
                fours: 1,
                sixes: 0,
                strikeRate: 82.35
            },
            batsmanNonStriker: {
                id: 2,
                name: "Aayan Afzal Khan",
                nickname: "Aayan",
                balls: 17,
                runs: 14,
                dots: 10,
                fours: 1,
                sixes: 0,
                strikeRate: 82.35
            },
            bowlerStriker: {
                id: 1,
                name: "Izharulhaq Naveed",
                overs: 2.4,
                runs: 7,
                economy: 2.63,
                maidens: 0,
                dots: 0,
                noBalls: 0,
                wides: 0,
                wickets: 2,
            },
            bowlerNonStriker: {
                id: 1,
                name: "Izharulhaq Naveed",
                overs: 2.4,
                runs: 7,
                economy: 2.63,
                maidens: 0,
                dots: 0,
                noBalls: 0,
                wides: 0,
                wickets: 2,
            },
            partnership: {
                runs: 16,
                balls: 12,
                bat1Id: 1,
                bat1Runs: 14,
                bat1Balls: 8,
                bat2Id: 2,
                bat2Runs: 4,
                bat2Balls: 4,
            },
            matchScoreDetails: {
                firstInnings: {
                    batTeamId: 1,
                    batTeamName: "Bangladesh",
                    batTeamCode: "ban",
                    score: 147,
                    wickets: 7,
                    overs: 19.3,
                },
                secondInnings: {
                    batTeamId: 283,
                    batTeamName: "India",
                    batTeamCode: "ind",
                    score: 54,
                    wickets: 10,
                    overs: 14.4
                },
                tossResults: {
                    tossWinnerId: 1,
                    tossWinnerName: "United Arab Emirates",
                    decision: "Bowling"
                }
            },
            latestPerformance: [
                {
                    runs: 19,
                    wickets: 3,
                    label: "Last 5 overs"
                },
                {
                    runs: 48,
                    wickets: 8,
                    label: "Last 10 overs"
                }
            ]
        }
    }
];