export const matches = [
    {
        id: 1,
        title: "2nd T20I",
        over: 20,
        seriesId: 1,
        venueId: 11,
        batTeamId: 2,
        runningInnings: 1,
        team1Id: 2,
        team2Id: 6,
        team1PlayersId: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        team2PlayersId: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        scorecardId: 1,
        commentaryId: 1,
        tossResult: {
            winnerId: 1,
            winnerName: "United Arab Emirates",
            winningTeamCode: "uae",
            decision: "bat"
        },
        matchResult: {
            winningTeamId: 27,
            winningMargin: 9,
            winByRuns: true,
            ballsRemaining: 0
        },
        momPlayerId: 1,
        stage: 0,
        time: "2024-03-25T07:03:29.109Z",
    },
    {
        id: 2,
        title: "1st T20I",
        over: 20,
        seriesId: 2,
        venueId: 5,
        batTeamId: 2,
        runningInnings: 1,
        team1Id: 2,
        team2Id: 6,
        scorecardId: 1,
        commentaryId: 1,
        team1PlayersId: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        team2PlayersId: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        tossResult: {
            winningTeamId: 1,
            winningTeamName: "United Arab Emirates",
            winningTeamCode: "uae",
            decision: "bowl"
        },
        matchResult: {
            winningTeamId: 27,
            winningMargin: 9,
            winByRuns: true,
            ballsRemaining: 0
        },
        momPlayerId: 1,
        stage: 1,
        time: "2024-03-25T07:03:29.109Z",
    },
    {
        id: 3,
        title: "1st T20I",
        over: 20,
        seriesId: 2,
        venueId: 5,
        batTeamId: 2,
        runningInnings: 1,
        team1Id: 2,
        team2Id: 6,
        team1PlayersId: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        team2PlayersId: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
        scorecardId: 1,
        commentaryId: 1,
        tossResult: {
            winningTeamId: 2,
            winningTeamName: "United Arab Emirates",
            winningTeamCode: "uae",
            decision: "bowl"
        },
        matchResult: {
            winningTeamId: 27,
            winningMargin: 9,
            winByRuns: true,
            ballsRemaining: 0
        },
        momPlayerId: 1,
        stage: 2,
        time: "2024-03-25T07:03:29.109Z",
    },
    {
        id: 4,
        title: "1st T20I",
        over: 20,
        seriesId: 2,
        venueId: 5,
        batTeamId: 2,
        runningInnings: 1,
        team1Id: 2,
        team2Id: 6,
        team1PlayersId: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        team2PlayersId: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        scorecardId: 1,
        commentaryId: 1,
        tossResult: {
            winningTeamId: 1,
            winningTeamName: "United Arab Emirates",
            winningTeamCode: "uae",
            decision: "bowl"
        },
        matchResult: {
            winningTeamId: 27,
            winningTeamName: "United Arab Emirates",
            winningTeamCode: "uae",
            winningMargin: 9,
            winBy: "run",
            ballsRemaining: 0
        },
        momPlayerId: 1,
        stage: 3,
        time: "2024-03-25T07:03:29.109Z",
    },
];
