export const scorecards = [
    {
        id: 1,
        matchId: 1,
        firstInnings: {
            batTeamDetails: {
                batTeamId: 1,
                batTeamName: "Bangladesh",
                batTeamCode: "ban",
                batsmanData: {
                    bat_1: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_2: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_3: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_4: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_5: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                }
            },
            bowlTeamDetails: {
                bowlTeamId: 2,
                bowlTeamName: "India",
                bowlTeamNickname: "ind",
                bowlersData: {
                    bowl_1: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_2: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_3: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_4: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_5: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    }
                }
            },
            scoreDetails: {
                overs: 18.5,
                runs: 150,
                runRate: 7.96,
                wickets: 10
            },
            extrasData: {
                total: 6,
                wides: 5,
                noBalls: 0,
                byes: 0,
                penalty: 0,
                legByes: 1
            },
            wicketsData: {
                wkt_1: {
                    batId: 1,
                    batName: "Simi Singh",
                    batNickname: "Simi",
                    wktNbr: 1,
                    wktOver: 16.5,
                    wktRuns: 128
                },
                wkt_2: {
                    batId: 2,
                    batName: "Balbirnie",
                    batNickname: "Balbirnie",
                    wktNbr: 2,
                    wktOver: 1.6,
                    wktRuns: 20,
                    ballNbr: 16
                }
            },
            partnershipsData: {
                pat_1: {
                    bat1Id: 1,
                    bat1Name: "Stirling",
                    bat1Nickname: "Stirling",
                    bat1Runs: 5,
                    bat1balls: 0,
                    bat1fours: 1,
                    bat1sixes: 0,
                    bat2Id: 2,
                    bat2Name: "Balbirnie",
                    bat2Nickname: "Balbirnie",
                    bat2Runs: 1,
                    bat2balls: 0,
                    bat2fours: 0,
                    bat2sixes: 0,
                    totalRuns: 6,
                    totalBalls: 6
                },
                pat_2: {
                    bat1Id: 1,
                    bat1Name: "Stirling",
                    bat1Nickname: "Stirling",
                    bat1Runs: 5,
                    bat1balls: 0,
                    bat1fours: 1,
                    bat1sixes: 0,
                    bat2Id: 2,
                    bat2Name: "Balbirnie",
                    bat2Nickname: "Balbirnie",
                    bat2Runs: 1,
                    bat2balls: 0,
                    bat2fours: 0,
                    bat2sixes: 0,
                    totalRuns: 6,
                    totalBalls: 6
                }
            }
        },
        secondInnings: {
            batTeamDetails: {
                batTeamId: 1,
                batTeamName: "Bangladesh",
                batTeamCode: "ban",
                batsmanData: {
                    bat_1: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_2: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_3: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_4: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_5: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                }
            },
            bowlTeamDetails: {
                bowlTeamId: 2,
                bowlTeamName: "India",
                bowlTeamNickname: "ind",
                bowlersData: {
                    bowl_1: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_2: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_3: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_4: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_5: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    }
                }
            },
            scoreDetails: {
                overs: 18.5,
                runs: 150,
                runRate: 7.96,
                wickets: 10
            },
            extrasData: {
                total: 6,
                wides: 5,
                noBalls: 0,
                byes: 0,
                penalty: 0,
                legByes: 1
            },
            wicketsData: {
                wkt_1: {
                    batId: 1,
                    batName: "Simi Singh",
                    batNickname: "Simi",
                    wktNbr: 1,
                    wktOver: 16.5,
                    wktRuns: 128
                },
                wkt_2: {
                    batId: 2,
                    batName: "Balbirnie",
                    batNickname: "Balbirnie",
                    wktNbr: 2,
                    wktOver: 1.6,
                    wktRuns: 20,
                    ballNbr: 16
                }
            },
            partnershipsData: {
                pat_1: {
                    bat1Id: 1,
                    bat1Name: "Stirling",
                    bat1Nickname: "Stirling",
                    bat1Runs: 5,
                    bat1balls: 0,
                    bat1fours: 1,
                    bat1sixes: 0,
                    bat2Id: 2,
                    bat2Name: "Balbirnie",
                    bat2Nickname: "Balbirnie",
                    bat2Runs: 1,
                    bat2balls: 0,
                    bat2fours: 0,
                    bat2sixes: 0,
                    totalRuns: 6,
                    totalBalls: 6
                },
                pat_2: {
                    bat1Id: 1,
                    bat1Name: "Stirling",
                    bat1Nickname: "Stirling",
                    bat1Runs: 5,
                    bat1balls: 0,
                    bat1fours: 1,
                    bat1sixes: 0,
                    bat2Id: 2,
                    bat2Name: "Balbirnie",
                    bat2Nickname: "Balbirnie",
                    bat2Runs: 1,
                    bat2balls: 0,
                    bat2fours: 0,
                    bat2sixes: 0,
                    totalRuns: 6,
                    totalBalls: 6
                }
            }
        }
    },
    {
        id: 2,
        matchId: 2,
        firstInnings: {
            batTeamDetails: {
                batTeamId: 1,
                batTeamName: "Bangladesh",
                batTeamCode: "ban",
                batsmanData: {
                    bat_1: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_2: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_3: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_4: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_5: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                }
            },
            bowlTeamDetails: {
                bowlTeamId: 2,
                bowlTeamName: "India",
                bowlTeamNickname: "ind",
                bowlersData: {
                    bowl_1: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_2: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_3: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_4: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_5: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    }
                }
            },
            scoreDetails: {
                overs: 18.5,
                runs: 150,
                runRate: 7.96,
                wickets: 10
            },
            extrasData: {
                total: 6,
                wides: 5,
                noBalls: 0,
                byes: 0,
                penalty: 0,
                legByes: 1
            },
            wicketsData: {
                wkt_1: {
                    batId: 1,
                    batName: "Simi Singh",
                    batNickname: "Simi",
                    wktNbr: 1,
                    wktOver: 16.5,
                    wktRuns: 128
                },
                wkt_2: {
                    batId: 2,
                    batName: "Balbirnie",
                    batNickname: "Balbirnie",
                    wktNbr: 2,
                    wktOver: 1.6,
                    wktRuns: 20,
                    ballNbr: 16
                }
            },
            partnershipsData: {
                pat_1: {
                    bat1Id: 1,
                    bat1Name: "Stirling",
                    bat1Nickname: "Stirling",
                    bat1Runs: 5,
                    bat1balls: 0,
                    bat1fours: 1,
                    bat1sixes: 0,
                    bat2Id: 2,
                    bat2Name: "Balbirnie",
                    bat2Nickname: "Balbirnie",
                    bat2Runs: 1,
                    bat2balls: 0,
                    bat2fours: 0,
                    bat2sixes: 0,
                    totalRuns: 6,
                    totalBalls: 6
                },
                pat_2: {
                    bat1Id: 1,
                    bat1Name: "Stirling",
                    bat1Nickname: "Stirling",
                    bat1Runs: 5,
                    bat1balls: 0,
                    bat1fours: 1,
                    bat1sixes: 0,
                    bat2Id: 2,
                    bat2Name: "Balbirnie",
                    bat2Nickname: "Balbirnie",
                    bat2Runs: 1,
                    bat2balls: 0,
                    bat2fours: 0,
                    bat2sixes: 0,
                    totalRuns: 6,
                    totalBalls: 6
                }
            }
        },
        secondInnings: {
            batTeamDetails: {
                batTeamId: 1,
                batTeamName: "Bangladesh",
                batTeamCode: "ban",
                batsmanData: {
                    bat_1: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_2: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_3: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_4: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                    bat_5: {
                        batId: 1,
                        batName: "Mahmudullah Riyadh",
                        batNickname: "Mahmudullah",
                        runs: 5,
                        balls: 10,
                        strikeRate: 50,
                        dots: 0,
                        ones: 0,
                        twos: 0,
                        threes: 0,
                        fours: 0,
                        fives: 0,
                        sixes: 0,
                        boundaries: 0,
                        outDetails: "c Ritwik Behera b Vatsal Vaghela",
                        bowlerId: 2,
                        fielderId: 3,
                        wicketCode: "caught"
                    },
                }
            },
            bowlTeamDetails: {
                bowlTeamId: 2,
                bowlTeamName: "India",
                bowlTeamNickname: "ind",
                bowlersData: {
                    bowl_1: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_2: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_3: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_4: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    },
                    bowl_5: {
                        bowlerId: 15475,
                        bowlName: "Nisarg Patel",
                        bowlNickname: "",
                        overs: 4,
                        maidens: 0,
                        runs: 29,
                        wickets: 2,
                        economy: 7.2,
                        no_balls: 0,
                        wides: 0,
                        dots: 0,
                        balls: 40
                    }
                }
            },
            scoreDetails: {
                overs: 18.5,
                runs: 150,
                runRate: 7.96,
                wickets: 10
            },
            extrasData: {
                total: 6,
                wides: 5,
                noBalls: 0,
                byes: 0,
                penalty: 0,
                legByes: 1
            },
            wicketsData: {
                wkt_1: {
                    batId: 1,
                    batName: "Simi Singh",
                    batNickname: "Simi",
                    wktNbr: 1,
                    wktOver: 16.5,
                    wktRuns: 128
                },
                wkt_2: {
                    batId: 2,
                    batName: "Balbirnie",
                    batNickname: "Balbirnie",
                    wktNbr: 2,
                    wktOver: 1.6,
                    wktRuns: 20,
                    ballNbr: 16
                }
            },
            partnershipsData: {
                pat_1: {
                    bat1Id: 1,
                    bat1Name: "Stirling",
                    bat1Nickname: "Stirling",
                    bat1Runs: 5,
                    bat1balls: 0,
                    bat1fours: 1,
                    bat1sixes: 0,
                    bat2Id: 2,
                    bat2Name: "Balbirnie",
                    bat2Nickname: "Balbirnie",
                    bat2Runs: 1,
                    bat2balls: 0,
                    bat2fours: 0,
                    bat2sixes: 0,
                    totalRuns: 6,
                    totalBalls: 6
                },
                pat_2: {
                    bat1Id: 1,
                    bat1Name: "Stirling",
                    bat1Nickname: "Stirling",
                    bat1Runs: 5,
                    bat1balls: 0,
                    bat1fours: 1,
                    bat1sixes: 0,
                    bat2Id: 2,
                    bat2Name: "Balbirnie",
                    bat2Nickname: "Balbirnie",
                    bat2Runs: 1,
                    bat2balls: 0,
                    bat2fours: 0,
                    bat2sixes: 0,
                    totalRuns: 6,
                    totalBalls: 6
                }
            }
        }
    }
];